###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = pkill rofi || bash ~/.config/rofi/launcher.sh
$screenShot_screen = grim "$(slurp)" - | wl-copy
$screenShot_region = grim -g "$(slurp)" - | wl-copy