###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = pkill rofi || bash ~/.config/rofi/launcher.sh
$screenShot_screen = hyprshot -m window -o "~/Pictures/Screenshots"
$screenShot_region = hyprshot -m region
$musicPlayerTui = rmpc